version: 2

build:
  os: ubuntu-22.04
  tools:
    python: '3.11'
  jobs:
    # https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-poetry
    # this is needed because we no longer list docs as an extra, but rather as a
    # poetry dependency group.
    post_create_environment:
      - pip install poetry
      - poetry config virtualenvs.create false
    post_install:
      - poetry install --no-interaction --with docs
